[package]
name = "rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poloto = "3.13.1"
reqwest = "0.11"
rss = "2.0"
tokio = { version = "1", features = ["full"] }
