name: Compile and Build

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd rs && cargo build --release --all-features
      - run: mv target/release/rs ../tools/build
      - run: bash deploy.sh

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "compile and build"
