name: Compile and Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd rs && cargo build --release --all-features

      - run: mv rs/target/release/rs tools/build

      - run: bash tools/deploy.sh

      - run: tools/tailwindcss-linux-x64 -i ./src/input.css -o ./dist/output.css --minify

      - uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "compile and build"
